Add devise
Perkir/tutu pull request #4
Opened 2016-09-30 23:26 UTC by Perkir

Подключить к проекту аутентификацию через Devise
Разделить приложение на пользовательскую и административную части. В административную часть имеет доступ только пользователи с правами администратора.
При покупке билета, билет должен привязываться к купившему его пользователю (залогиненному), при этом, id пользователя не должен передаваться в параметрах запроса или полях формы, в т.ч. скрытых (используйте current_user в контроллере для этого)
Залогиненный пользователь может посмотреть список всех своих купленных билетов, каждый билет в отдельности, а также удалить билет
Администратор может просматривать список всех билетов в системе, каждый в отдельности, редактировать билеты и удалять их.

Усложненное задание:

При регистрации пользователя запрашивать его имя и фамилию и после входа, выводить "Привет, <имя пользователя>!" 
После успешного входа, перенаправлять обычных пользователей на страницу поиска билетов, а админов - на страницу, где перечислены ссылки на управление ресурсами приложения (статья из wiki devise: github.com:-Redirect-to-a-specific-page-on-successful-sign-in-and-sign-out).

2016-10-02 15:35 UTC, psylone requested changes

2016-10-02 15:35 UTC, psylone commented on app/controllers/application_controller.rb
> +    devise_parameter_sanitizer.for(:sign_up){ |u| u.permit(:first_name, :last_name) }
Метод `#for` был запрещён и сейчас отсутствует: http://stackoverflow.com/a/38450172/825563

2016-10-02 15:35 UTC, psylone commented on app/views/devise/registrations/new.html.erb
> +      <%= f.label :first_name %><br/>
`first_name` и `last_name` нужно добавить в модель `User`.

2016-10-02 15:35 UTC, psylone commented on app/views/admin/trains/edit.html.erb
>  <%= render 'form' %>
Во фрагменте `form` нужно будет учитывать namespace для админа.

2016-10-02 15:35 UTC, psylone commented on app/controllers/admin/trains_controller.rb
> +class Admin::TrainsController < ApplicationController
Я могу из-под пользователя который не является админом создавать поезда.

2016-10-02 15:35 UTC, psylone commented on app/models/ticket.rb
>      self.number = (0...8).map { syms[rand(syms.size)] }.join
Это можно упростить до: `["a".."z", "A".."Z", "0".."9"].map(&:to_a).flatten.sample(8).join`.

2016-10-02 15:35 UTC, psylone commented on app/controllers/tickets_controller.rb
> +    @ticket = Ticket.find(params[:id])
Лучше искать через `current_user.tickets.find(params[:id])`, иначе возможно подменить идентификатор билета и удалить чужой билет.

2016-10-02 15:35 UTC, psylone commented on app/controllers/tickets_controller.rb
> +  def show_my
На самом деле, это просто `index` согласно соглашениям.

2016-10-02 15:35 UTC, psylone commented on app/views/searches/show.html.erb
>                      <td>
Вложенные формы в HTML не допускаются: http://stackoverflow.com/questions/379610/can-you-nest-html-forms

Поэтому при нажатии на покупку билета будут трудности.

2016-10-02 15:35 UTC, psylone commented on app/views/searches/show.html.erb
>                      <td>
Кроме того, покупка билета предполагает получение формы для заполнения паспортных данных, а это `GET` запрос.

2016-10-03 07:23 UTC, vkurennov approved these changes
Принято, но учти замечания

2016-10-03 07:23 UTC, vkurennov commented on app/controllers/tickets_controller.rb
> +    current_user.tickets << @ticket
Можно сразу писать `current_user.ticekts.new(...)`

2016-10-03 07:23 UTC, vkurennov commented on app/controllers/tickets_controller.rb
> +    redirect_to root_path, alert: "Доступ запрещён!" unless @ticket.user == current_user
Смысла в этой проверке больше нет, т.к. ты ищещь сразу билеты у current_user, если такого билета не будет, то в dev-режиме рельсы выбросят исключение, а в prod - 404 ошибку (не найдено).

2016-10-03 07:23 UTC, vkurennov commented on app/views/common/_user_status.html.erb
> +    <%= link_to 'Выйти', destroy_user_session_path, method: :delete %>
Эта же ссылка в 4-й строке прописана

2016-10-03 20:14 UTC, merged